openapi: 3.0.3
info:
  title: Lunch Layout - API 1.0
  description: "AR application for cafes"
  version: 1.0.2
paths:
  /reviews:
    post:
      tags:
        - reviews
      summary: Add a new review
      parameters:
        - in: body
          name: review
          description: review data
          required: true
          schema:
            $ref: "#/components/schemas/Review"
      description: ''
      operationId: sendView
      responses:
        '200':
          description: successful operation        
        '404':
          description: Bad request
        '500':
          description: Server error
  /cafes/{cafe_id}:
    get:
      tags:
        - cafes
      summary: Get dishes of selected cafe
      operationId: getDishes
      parameters:
        - name: cafe_id
          in: path
          description: ''
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cafe' 
        '404':
          description: Bad request
        '500':
          description: Server error
  /dishes/{dish_id}:
    get:
      tags:
        - dishes
      summary: Get dish info
      operationId: getDishById
      parameters:
        - name: dish_id
          in: path
          description: ''
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dish' 
        '404':
          description: Bad request
        '500':
          description: Server error
          
components:
  schemas:
    Review:
      type: object
      properties:
        rate:
          type: integer
          description: review rate
        text:
          type: string
          description: review text
    Dish:
      type: object
      properties:
        id:
          type: string
          description: dish id
        name:
          type: string
          description: dish name
        model:
          type: string
          description: link to gltf model
        content:
          type: object
          description: dish media content
          properties:   
            facts:
              type: array
              description: dish facts
              items:
                type: object 
                properties:
                  description:
                    type: string
                    description: fact about dish
                  img:
                    type: string
                    description: link to dish img 
            videos:
              type: array
              description: dish videos
              items:
                type: object 
                properties:
                  title:
                    type: string
                    description: title of video about dish
                  src:
                    type: string
                    description: link to video about dish
        info:
          type: object
          properties:
            description:
              type: string
              description: dish description 
            price:
              type: string
              description: dish price
            ingredients:
              type: array
              description: dish ingredients
              items:
                type: string
            allergens:
              type: array
              description: dish allergens
              items:
                type: string
            kbzhu:
              type: object
              properties:
                calories:
                  type: integer
                  description: dish calories
                proteins:
                  type: integer
                  description: dish proteins
                fats:
                  type: integer
                  description: dish fats
                carbohydrates:
                  type: integer
                  description: dish carbohydrates
              
                

    Cafe:
      type: object
      properties:
        id:
          type: string
          description: cafe id
        name:
          type: string
          description: cafe name
        logo:
          type: string
          description: link to logotype of cafe  
        dishes:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: dish id
              name:
                type: string
                description: dish name
              price:
                type: integer
                description: dish price
              img:
                type: string
                description: dish img link
          
