default:
  server:
    host: localhost
    port: 5000
    protocol: https
  database:
    host: 192.168.0.127
    port: 27017
    protocol: mongodb
    name: lunchLayout
  clients:
    - host: 192.168.0.127
      port: 3000
      protocol: https
    - host: localhost
      port: 3000
      protocol: https